#pragma once

#include "DnniInference.h"
#include "DnniReader.h"
#include "PhoneSet.h"
#include "PhonemeTiming.h"

#include <juce_core/juce_core.h>

#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

namespace sv::synthesis
{
/**
 * @brief Input musical note for the pitch prediction pipeline.
 */
struct PitchNote
{
    TimingSyllable syllable;          ///< Note syllable with timing, pitch, and lyric phonemes.
    bool isBreath = false;            ///< True if this note represents an aspiration / breath intake.
    bool isSilence = false;           ///< True if this note is a silence / rest separator.
    bool isContinuation = false;       ///< True if this note continues the pitch/phoneme of previous note.
    bool isRap = false;                ///< True if this note uses rap intonation rather than melodic singing.
    int tone = 0;                     ///< Tone modifier / pitch register offset.
    float vibratoModulation = 1.0f;   ///< Scaling factor applied to vibrato speed and depth.
};

/**
 * @brief Output container for feature frames generated by the pitch frontend encoder.
 */
struct PitchFeatureOutput
{
    DnniTensor noteFeatures;                       ///< Encoded feature tensor on the 5ms grid.
    std::vector<std::size_t> noteFrameCounts;      ///< Number of 5ms frames spanned by each note.
    std::vector<std::size_t> phonemeFrameCounts;   ///< Number of 5ms frames spanned by each phoneme.
    std::vector<std::size_t> phonemeCategories;    ///< Phonetic category ID of each phoneme.
    std::vector<std::size_t> phonemeLanguages;     ///< Language ID of each phoneme.
    std::vector<std::uint8_t> phonemeVowels;       ///< 1 if phoneme is vowel/nucleus, 0 if consonant/silence.
};

/**
 * @brief Frontend feature encoder for the neural pitch prediction model (`gen5` pitch model).
 *
 * Responsibilities:
 * - Projects discrete notes and phoneme durations onto an acoustic frame grid (typically 5 ms frames = 200 Hz).
 * - Extracts continuous pitch and timing context features.
 * - Applies z-score normalization (subtracting `means`, multiplying by `scales`).
 * - Denormalizes predicted pitch outputs into absolute MIDI pitch numbers (semitones).
 */
class PitchFeatures
{
public:
    /**
     * @brief Loads the frontend descriptor and feature normalization statistics from a DNNI model.
     */
    [[nodiscard]] juce::Result load(const DnniReader& reader, std::size_t nodeIndex);

    /**
     * @brief Returns the acoustic frame interval in seconds (typically 0.005f = 5 ms).
     */
    [[nodiscard]] float getFrameIntervalSeconds() const noexcept;

    /**
     * @brief Returns total number of phonetic categories defined in the inventory.
     */
    [[nodiscard]] std::size_t getPhonemeCategoryCount() const noexcept;

    /**
     * @brief Returns number of distinct language configurations supported.
     */
    [[nodiscard]] std::size_t getLanguageCount() const noexcept;

    /**
     * @brief Encodes note and phoneme sequences into normalized feature frames.
     */
    [[nodiscard]] juce::Result encode(std::span<const PitchNote> notes, std::span<const PhonemeDuration> phonemes, PitchFeatureOutput& output) const;

    /**
     * @brief Converts normalized pitch predictions back to standard MIDI pitch semitones.
     */
    [[nodiscard]] juce::Result denormalizePitch(std::span<const float> normalizedPitch, std::vector<float>& midiPitch) const;

private:
    std::vector<PhoneSet> phoneSets;
    PhoneSet unifiedPhoneSet;
    std::vector<float> means;
    std::vector<float> scales;
    float frameIntervalSeconds = 0.0f;
};

} // namespace sv::synthesis
